
services:
  simpliroute_webhook_server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./settings/.env
    environment:
      ORACLE_INSTANT_CLIENT: /opt/oracle/instantclient
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw
    entrypoint: ["python", "simpliroute_webhook_server.py"]
    command: []
    restart: unless-stopped
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  simpliroute_send:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./settings/.env
    environment:
      ORACLE_INSTANT_CLIENT: /opt/oracle/instantclient
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw
    entrypoint: ["python", "simpliroute_send.py"]
    command: []
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
