
services:
  integrador:
    image: integradorsr-integrador:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview"
      SIMPLIR_ROUTE_TOKEN: ""

  integrador_limit1:
    image: integradorsr-integrador_limit1:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview --limit 1"
      SIMPLIR_ROUTE_TOKEN: ""

  integrador_preview:
    image: integradorsr-integrador_preview:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview"
      SIMPLIR_ROUTE_TOKEN: ""

  integrador_preview_limit1:
    image: integradorsr-integrador_preview_limit1:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview --limit 1"
      SIMPLIR_ROUTE_TOKEN: ""

  integrador_service:
    image: integradorsr-simpliroute:prod
    env_file:
      - ./settings/.env.test
