version: '3.8'

x-integrador-env: &integrador-env
  ORACLE_INSTANT_CLIENT: /opt/oracle/instantclient

services:
  integrador: &integrador-base
    build:
      context: .
      dockerfile: Dockerfile
    image: integradorsr-simpliroute:prod
    env_file:
      - ./settings/.env
    environment:
      <<: *integrador-env
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  integrador_limit1:
    <<: *integrador-base
    environment:
      <<: *integrador-env
      SIMPLIROUTE_AUTO_COMMAND: "send --limit 1 --send"

  integrador_preview:
    <<: *integrador-base
    environment:
      <<: *integrador-env
      SIMPLIROUTE_AUTO_COMMAND: "preview"

  integrador_preview_limit1:
    <<: *integrador-base
    environment:
      <<: *integrador-env
      SIMPLIROUTE_AUTO_COMMAND: "preview --limit 1"
