version: '3.8'
services:
  integrador:
    build:
      context: .
      dockerfile: Dockerfile
    image: integradorsr-simpliroute:prod
    env_file:
      - ./settings/.env
    environment:
      - USE_GNEXUM_DB=1
      - SIMPLIROUTE_DRY_RUN=1
      - DRY_RUN_SAVE_PAYLOADS=1
      - ORACLE_INSTANT_CLIENT=/opt/oracle/instantclient
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
