services:
  simpliroute_send:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./settings/.env
    environment:
      ORACLE_INSTANT_CLIENT: /opt/oracle/instantclient
    entrypoint: ["python", "simpliroute_send.py"]
    command: []
    restart: unless-stopped
    ports:
      - "8001:8001"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
 
 
#  IMPORTANTE:
    # volumes aqui substitui o volumes herdado do integrador-base,
    # então precisamos repetir os volumes do base e adicionar os logs.
    volumes:
      # mounts originais
      - ./settings:/simple_route/Integrador-SR-main/settings:ro

      #  log estruturado: /app/logs/webhook_server.log -> host ./logs/webhook_server/
      - ./logs/webhook_server:/simple_route/Integrador-SR-main/app/simpliroute_webhook_error_logs:rw

      #  payloads recebidos: /app/simpliroute_send_logs/webhook_*.json -> host ./logs/webhook_send_error/
      - ./logs/webhook_payloads:/simple_route/Integrador-SR-main/app/simpliroute_send_error_logs:rw
 
 
  simpliroute_webhook_server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./settings/.env
    environment:
      ORACLE_INSTANT_CLIENT: /opt/oracle/instantclient
    entrypoint: ["python", "simpliroute_webhook_server.py"]
    command: []
    restart: unless-stopped
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
 
 
#  IMPORTANTE:
    # volumes aqui substitui o volumes herdado do integrador-base,
    # então precisamos repetir os volumes do base e adicionar os logs.
    volumes:
     # mounts originais
      - ./settings:/simple_route/Integrador-SR-main/settings:ro

      #  log estruturado: /app/logs/webhook_server.log -> host ./logs/webhook_server/
      - ./logs/webhook_server:/simple_route/Integrador-SR-main/app/simpliroute_webhook_error_logs:rw

      #  payloads recebidos: /app/simpliroute_send_logs/webhook_*.json -> host ./logs/webhook_send_error/
      - ./logs/webhook_payloads:/simple_route/Integrador-SR-main/app/simpliroute_send_error_logs:rw
      