
services:
  integrador:
    image: ghcr.io/DBCBR/integradorsr-integrador:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview"
      SIMPLIR_ROUTE_TOKEN: ""
      SIMPLIROUTE_DISABLE_SEND: "1"
      SIMPLIROUTE_DRY_RUN: "1"
      SIMPLIROUTE_POLL_WHERE: "1=0"
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw

  integrador_limit1:
    image: ghcr.io/DBCBR/integradorsr-integrador_limit1:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview --limit 1"
      SIMPLIR_ROUTE_TOKEN: ""
      SIMPLIROUTE_DISABLE_SEND: "1"
      SIMPLIROUTE_DRY_RUN: "1"
      SIMPLIROUTE_POLL_WHERE: "1=0"
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw

  integrador_preview:
    image: ghcr.io/DBCBR/integradorsr-integrador_preview:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview"
      SIMPLIR_ROUTE_TOKEN: ""
      SIMPLIROUTE_DISABLE_SEND: "1"
      SIMPLIROUTE_DRY_RUN: "1"
      SIMPLIROUTE_POLL_WHERE: "1=0"
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw

  integrador_preview_limit1:
    image: ghcr.io/DBCBR/integradorsr-integrador_preview_limit1:latest
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_AUTO_COMMAND: "preview --limit 1"
      SIMPLIR_ROUTE_TOKEN: ""
      SIMPLIROUTE_DISABLE_SEND: "1"
      SIMPLIROUTE_DRY_RUN: "1"
      SIMPLIROUTE_POLL_WHERE: "1=0"
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw

  integrador_service:
    image: ghcr.io/DBCBR/integradorsr-simpliroute:prod
    env_file:
      - ./settings/.env.test
    environment:
      SIMPLIROUTE_DISABLE_SEND: "1"
      SIMPLIROUTE_DRY_RUN: "1"
      SIMPLIROUTE_POLL_WHERE: "1=0"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./settings:/app/settings:ro
      - ./data/output:/app/data/output:rw
      - ./data/work:/app/data/work:rw
