version: '3.8'
services:
  simpliroute:
    build: .
    container_name: simpliroute_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./settings/.env
    volumes:
      - ./:/app:ro
